version: '3.4'

services:
  braindumpapi:
    image: ${DOCKER_REGISTRY-}braindumpapi
    build:
      context: .
      dockerfile: BrainDumpApi/Dockerfile

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 5650:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
